In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
url = 'https://raw.githubusercontent.com/ybifoundation/Dataset/main/Movies%20Recommendation.csv'
df = pd.read_csv(url,encoding='unicode_escape')

In [3]:
df.head()

Movie_ID      Movie_Title                       Movie_Genre Movie_Language  \
0         1       Four Rooms                      Crime Comedy             en   
1         2        Star Wars  Adventure Action Science Fiction             en   
2         3     Finding Nemo                  Animation Family             en   
3         4     Forrest Gump              Comedy Drama Romance             en   
4         5  American Beauty                             Drama             en   

   Movie_Budget  Movie_Popularity Movie_Release_Date  Movie_Revenue  \
0       4000000         22.876230         09-12-1995        4300000   
1      11000000        126.393695         25-05-1977      775398007   
2      94000000         85.688789         30-05-2003      940335536   
3      55000000        138.133331         06-07-1994      677945399   
4      15000000         80.878605         15-09-1999      356296601   

   Movie_Runtime  Movie_Vote  ...  \
0           98.0         6.5  ...   
1          121.0         8.1  ...   
2          100.0         7.6  ...   
3          142.0         8.2  ...   
4          122.0         7.9  ...   

                                      Movie_Homepage  \
0                                                NaN   
1  http://www.starwars.com/films/star-wars-episod...   
2              http://movies.disney.com/finding-nemo   
3                                                NaN   
4                      http://www.dreamworks.com/ab/   

                                      Movie_Keywords  \
0          hotel new year's eve witch bet hotel room   
1        android galaxy hermit death star lightsaber   
2  father son relationship harbor underwater fish...   
3  vietnam veteran hippie mentally disabled runni...   
4  male nudity female nudity adultery midlife cri...   

                                      Movie_Overview  \
0  It's Ted the Bellhop's first night on the job....   
1  Princess Leia is captured and held hostage by ...   
2  Nemo, an adventurous young clownfish, is unexp...   
3  A man with a low IQ has accomplished great thi...   
4  Lester Burnham, a depressed suburban father in...   

                              Movie_Production_House  \
0  [{"name": "Miramax Films", "id": 14}, {"name":...   
1  [{"name": "Lucasfilm", "id": 1}, {"name": "Twe...   
2     [{"name": "Pixar Animation Studios", "id": 3}]   
3          [{"name": "Paramount Pictures", "id": 4}]   
4  [{"name": "DreamWorks SKG", "id": 27}, {"name"...   

                            Movie_Production_Country  \
0  [{"iso_3166_1": "US", "name": "United States o...   
1  [{"iso_3166_1": "US", "name": "United States o...   
2  [{"iso_3166_1": "US", "name": "United States o...   
3  [{"iso_3166_1": "US", "name": "United States o...   
4  [{"iso_3166_1": "US", "name": "United States o...   

                      Movie_Spoken_Language  \
0  [{"iso_639_1": "en", "name": "English"}]   
1  [{"iso_639_1": "en", "name": "English"}]   
2  [{"iso_639_1": "en", "name": "English"}]   
3  [{"iso_639_1": "en", "name": "English"}]   
4  [{"iso_639_1": "en", "name": "English"}]   

                                       Movie_Tagline  \
0  Twelve outrageous guests. Four scandalous requ...   
1       A long time ago in a galaxy far, far away...   
2  There are 3.7 trillion fish in the ocean, they...   
3  The world will never be the same, once you've ...   
4                                       Look closer.   

                                          Movie_Cast  \
0  Tim Roth Antonio Banderas Jennifer Beals Madon...   
1  Mark Hamill Harrison Ford Carrie Fisher Peter ...   
2  Albert Brooks Ellen DeGeneres Alexander Gould ...   
3  Tom Hanks Robin Wright Gary Sinise Mykelti Wil...   
4  Kevin Spacey Annette Bening Thora Birch Wes Be...   

                                          Movie_Crew   Movie_Director  
0  [{'name': 'Allison Anders', 'gender': 1, 'depa...   Allison Anders  
1  [{'name': 'George Lucas', 'gender': 2, 'depart...     George Lucas  
2  [{'na

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Movie_ID                  4760 non-null   int64  
 1   Movie_Title               4760 non-null   object 
 2   Movie_Genre               4760 non-null   object 
 3   Movie_Language            4760 non-null   object 
 4   Movie_Budget              4760 non-null   int64  
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object 
 7   Movie_Revenue             4760 non-null   int64  
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64  
 11  Movie_Homepage            1699 non-null   object 
 12  Movie_Keywords            4373 non-null   object 
 13  Movie_Overview            4757 non-null   object 
 14  Movie_Pr

In [5]:
df.dropna()

Movie_ID                                        Movie_Title  \
1            2                                          Star Wars   
2            3                                       Finding Nemo   
4            5                                    American Beauty   
9           10  Pirates of the Caribbean: The Curse of the Bla...   
10          11                                  Kill Bill: Vol. 1   
...        ...                                                ...   
4728      4755                                     Time to Choose   
4737      4765                                           Bad Moms   
4743      4772                                       Fight Valley   
4745      4774                                              Kicks   
4748      4777                                      The Dog Lover   

                           Movie_Genre Movie_Language  Movie_Budget  \
1     Adventure Action Science Fiction             en      11000000   
2                     Animation Family             en      94000000   
4                                Drama             en      15000000   
9             Adventure Fantasy Action             en     140000000   
10                        Action Crime             en      30000000   
...                                ...            ...           ...   
4728                       Documentary             en       3500000   
4737                            Comedy             en      20000000   
4743                      Action Drama             en      27000000   
4745                         Adventure             en             0   
4748                             Drama             en       2000000   

      Movie_Popularity Movie_Release_Date  Movie_Revenue  Movie_Runtime  \
1           126.393695         25-05-1977      775398007          121.0   
2            85.688789         30-05-2003      940335536          100.0   
4            80.878605         15-09-1999      356296601          122.0   
9           271.972889         09-07-2003      655011224          143.0   
10           79.754966         10-10-2003      180949000          111.0   
...                ...                ...            ...            ...   
4728          1.618138         04-09-2015              0          100.0   
4737         42.512296         28-07-2016      183936074          100.0   
4743          1.224105         22-07-2016              0           90.0   
4745          3.467923         09-09-2016              0           80.0   
4748          1.193219         08-07-2016              0          101.0   

      Movie_Vote  ...                                     Movie_Homepage  \
1            8.1  ...  http://www.starwars.com/films/star-wars-episod...   
2            7.6  ...              http://movies.disney.com/finding-nemo   
4            7.9  ...                      http://www.dreamworks.com/ab/   
9            7.5  ...  http://disney.go.com/disneyvideos/liveaction/p...   
10           7.7  ...   http://www.miramax.com/movie/kill-bill-volume-1/   
...          ...  ...                                                ...   
4728         0.0  ...                        http://www.timetochoose.com   
4737         6.3  ...                      http://stxmovies.com/badmoms/   
4743         3.9  ...                        http://www.fightvalley.com/   
4745         7.5  ...                 http://www.focusfeatures.com/kicks   
4748         5.3  ...                   http://www.thedoglovermovie.com/   

                                         Movie_Keywords  \
1           android galaxy hermit death star lightsaber   
2     father son relationship harbor underwater fish...   
4     male nudity female nudity adultery midlife cri...   
9     exotic island blacksmith east india trading co...   
10           japan coma martial arts kung fu underworld   
...                                                 ...   
4728                         climate change documentary   
4737                   alcohol bar par

In [6]:
df.dropna()

Movie_ID                                        Movie_Title  \
1            2                                          Star Wars   
2            3                                       Finding Nemo   
4            5                                    American Beauty   
9           10  Pirates of the Caribbean: The Curse of the Bla...   
10          11                                  Kill Bill: Vol. 1   
...        ...                                                ...   
4728      4755                                     Time to Choose   
4737      4765                                           Bad Moms   
4743      4772                                       Fight Valley   
4745      4774                                              Kicks   
4748      4777                                      The Dog Lover   

                           Movie_Genre Movie_Language  Movie_Budget  \
1     Adventure Action Science Fiction             en      11000000   
2                     Animation Family             en      94000000   
4                                Drama             en      15000000   
9             Adventure Fantasy Action             en     140000000   
10                        Action Crime             en      30000000   
...                                ...            ...           ...   
4728                       Documentary             en       3500000   
4737                            Comedy             en      20000000   
4743                      Action Drama             en      27000000   
4745                         Adventure             en             0   
4748                             Drama             en       2000000   

      Movie_Popularity Movie_Release_Date  Movie_Revenue  Movie_Runtime  \
1           126.393695         25-05-1977      775398007          121.0   
2            85.688789         30-05-2003      940335536          100.0   
4            80.878605         15-09-1999      356296601          122.0   
9           271.972889         09-07-2003      655011224          143.0   
10           79.754966         10-10-2003      180949000          111.0   
...                ...                ...            ...            ...   
4728          1.618138         04-09-2015              0          100.0   
4737         42.512296         28-07-2016      183936074          100.0   
4743          1.224105         22-07-2016              0           90.0   
4745          3.467923         09-09-2016              0           80.0   
4748          1.193219         08-07-2016              0          101.0   

      Movie_Vote  ...                                     Movie_Homepage  \
1            8.1  ...  http://www.starwars.com/films/star-wars-episod...   
2            7.6  ...              http://movies.disney.com/finding-nemo   
4            7.9  ...                      http://www.dreamworks.com/ab/   
9            7.5  ...  http://disney.go.com/disneyvideos/liveaction/p...   
10           7.7  ...   http://www.miramax.com/movie/kill-bill-volume-1/   
...          ...  ...                                                ...   
4728         0.0  ...                        http://www.timetochoose.com   
4737         6.3  ...                      http://stxmovies.com/badmoms/   
4743         3.9  ...                        http://www.fightvalley.com/   
4745         7.5  ...                 http://www.focusfeatures.com/kicks   
4748         5.3  ...                   http://www.thedoglovermovie.com/   

                                         Movie_Keywords  \
1           android galaxy hermit death star lightsaber   
2     father son relationship harbor underwater fish...   
4     male nudity female nudity adultery midlife cri...   
9     exotic island blacksmith east india trading co...   
10           japan coma martial arts kung fu underworld   
...                                                 ...   
4728                         climate change documentary   
4737                   alcohol bar par

In [7]:
df_features = df[['Movie_Genre','Movie_Spoken_Language','Movie_Keywords','Movie_Production_Country','Movie_Cast']]

In [8]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Movie_Genre               4760 non-null   object
 1   Movie_Spoken_Language     4760 non-null   object
 2   Movie_Keywords            4373 non-null   object
 3   Movie_Production_Country  4760 non-null   object
 4   Movie_Cast                4733 non-null   object
dtypes: object(5)
memory usage: 186.1+ KB


In [9]:
df_features = df_features.dropna()

In [10]:
X = df_features['Movie_Genre']+' '+df_features['Movie_Spoken_Language']+' '+df_features['Movie_Keywords']+' '+df_features['Movie_Production_Country']+' '+df_features['Movie_Cast']

In [11]:
X

0       Crime Comedy [{"iso_639_1": "en", "name": "Eng...
1       Adventure Action Science Fiction [{"iso_639_1"...
2       Animation Family [{"iso_639_1": "en", "name": ...
3       Comedy Drama Romance [{"iso_639_1": "en", "nam...
4       Drama [{"iso_639_1": "en", "name": "English"}]...
                              ...                        
4751    Horror [{"iso_639_1": "en", "name": "English"}...
4752    History Drama War Action [{"iso_639_1": "en", ...
4754    Action Adventure Animation Family Fantasy [{"i...
4757    Thriller Drama [{"iso_639_1": "en", "name": "E...
4759    Documentary [] music actors legendary perfomer...
Length: 4364, dtype: object

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tfidf = TfidfVectorizer()

In [14]:

X = tfidf.fit_transform(X)

In [15]:
X

<4364x12800 sparse matrix of type '<class 'numpy.float64'>'
	with 131347 stored elements in Compressed Sparse Row format>

In [16]:

from sklearn.metrics.pairwise import cosine_similarity

In [17]:
Similarity_Score = cosine_similarity(X)

In [18]:
print(Similarity_Score)
Similarity_Score.shape

[[1.         0.01968975 0.01783883 ... 0.12983487 0.02294662 0.00632509]
 [0.01968975 1.         0.01752616 ... 0.05314496 0.02254441 0.00621422]
 [0.01783883 0.01752616 1.         ... 0.05387388 0.02042515 0.00563006]
 ...
 [0.12983487 0.05314496 0.05387388 ... 1.         0.02866548 0.00811751]
 [0.02294662 0.02254441 0.02042515 ... 0.02866548 1.         0.00724212]
 [0.00632509 0.00621422 0.00563006 ... 0.00811751 0.00724212 1.        ]]


(4364, 4364)

In [19]:
Fav_Movie_Name = input('Enter your favourite movie name:')

Enter your favourite movie name:new york


In [20]:
All_Movies_Title = df['Movie_Title'].tolist()

In [21]:
import difflib as dl

In [22]:
Movie_Recommendation =  dl.get_close_matches(Fav_Movie_Name,All_Movies_Title)

In [23]:
print(Movie_Recommendation)
Close_Match = Movie_Recommendation[0]

['Network']


In [24]:
Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)
Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)
len(Recommendation_Score)

1794
[(0, 0.02066225511633454), (1, 0.020300088060842224), (2, 0.01839179919117045), (3, 0.023924416858436416), (4, 0.09876371371529008), (5, 0.10340603940425756), (6, 0.048395913238105215), (7, 0.010657216287292992), (8, 0.059660972319038684), (9, 0.018930729134047884), (10, 0.03898064113067241), (11, 0.03748299423560738), (12, 0.057738798870529635), (13, 0.02068217895946615), (14, 0.018481224953324486), (15, 0.025730021389674552), (16, 0.011388909709757745), (17, 0.037850142949650535), (18, 0.034322595405802646), (19, 0.029155126572654087), (20, 0.024754114274369104), (21, 0.07706683321117237), (22, 0.03194312830178951), (23, 0.04894454771691634), (24, 0.02673192119533419), (25, 0.07798103323975995), (26, 0.022812086092108632), (27, 0.020358130910353153), (28, 0.07191857495396611), (29, 0.045056691061327765), (30, 0.020232141889775557), (31, 0.04306151824682405), (32, 0.012969451553539086), (33, 0.03545805856507796), (34, 0.023754478888863173), (35, 0.036746365814307166), (36, 0.0215

4364

In [25]:
Sorted_Similer_Movies = sorted(Recommendation_Score, key=lambda x:x[1],reverse = True)
print(Sorted_Similer_Movies)

[(1794, 1.0), (1703, 0.17976419494181883), (403, 0.16581928886638034), (3078, 0.14993650923034876), (4006, 0.14578815083447352), (1243, 0.14501765424622565), (857, 0.1429048410899722), (3161, 0.14276495747419923), (378, 0.1378182139285425), (3777, 0.1366008562101538), (3527, 0.13268070640851834), (998, 0.12723617941308538), (2928, 0.12568674492052567), (3408, 0.12492998385129955), (940, 0.12187522052764269), (2948, 0.12152528470408504), (99, 0.11977759020781246), (574, 0.1187076271676527), (332, 0.11853473030224458), (210, 0.11523256680019064), (220, 0.11474329985023876), (4172, 0.11409326700173365), (1219, 0.1138101420171282), (1626, 0.11325842509928176), (746, 0.1120300403157148), (3748, 0.1119533556104856), (321, 0.11191346691785746), (1046, 0.11042060048994255), (4054, 0.11002164585830987), (3158, 0.1085835780189299), (2793, 0.10836670882734356), (3136, 0.10779288063325265), (3649, 0.1070287028169626), (137, 0.10557437227331244), (3633, 0.10506987053488928), (2271, 0.10481010742083

In [26]:
print('Top 5 movies according to your choice:\n')
i=1
for movie in Sorted_Similer_Movies:
    index=movie[0]
    title_from_index = df[df.index==index]['Movie_Title'].values[0]
    if(i<6):
        print(i,'')

Top 5 movies according to your choice:

1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
1 
