In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_digits

In [3]:
df = load_digits()

In [4]:
df.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
df.images.shape

(1797, 8, 8)

In [6]:
df.images[0].shape

(8, 8)

In [7]:
n_samples = len(df.images)

In [8]:
data = df.images.reshape(n_samples, -1)

In [9]:
data.shape

(1797, 64)

In [10]:
data.min()

0.0

In [11]:
data.max()

16.0

In [12]:
data = data/16

In [13]:
data.min()

0.0

In [14]:
data.max()

1.0

In [15]:
data

array([[0.    , 0.    , 0.3125, ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.625 , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 1.    , 0.5625, 0.    ],
       ...,
       [0.    , 0.    , 0.0625, ..., 0.375 , 0.    , 0.    ],
       [0.    , 0.    , 0.125 , ..., 0.75  , 0.    , 0.    ],
       [0.    , 0.    , 0.625 , ..., 0.75  , 0.0625, 0.    ]])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(data,df.target,train_size=0.7,test_size=0.3)

In [18]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1257, 64), (540, 64), (1257,), (540,))

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf = RandomForestClassifier()

In [22]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [23]:
y_pred = rf.predict(X_test)

In [24]:
y_pred

array([7, 3, 8, 5, 3, 2, 3, 4, 6, 1, 6, 5, 2, 7, 1, 5, 0, 7, 3, 7, 9, 9,
       6, 7, 4, 0, 6, 1, 2, 4, 4, 4, 4, 0, 1, 0, 2, 4, 2, 4, 9, 0, 8, 0,
       4, 2, 7, 6, 4, 4, 5, 2, 4, 3, 8, 2, 9, 1, 8, 5, 5, 5, 1, 0, 6, 3,
       8, 3, 7, 8, 6, 0, 0, 2, 1, 3, 9, 3, 8, 5, 0, 1, 6, 4, 7, 1, 2, 8,
       7, 8, 4, 4, 0, 7, 7, 4, 4, 5, 4, 7, 7, 8, 4, 8, 0, 1, 1, 6, 2, 7,
       1, 3, 1, 3, 4, 2, 8, 0, 5, 4, 3, 7, 4, 3, 3, 4, 5, 9, 3, 3, 8, 0,
       4, 6, 5, 4, 4, 4, 1, 1, 5, 3, 2, 8, 1, 0, 7, 6, 8, 5, 0, 9, 6, 1,
       6, 7, 6, 1, 3, 4, 5, 4, 1, 1, 9, 1, 9, 3, 5, 8, 3, 6, 4, 6, 1, 3,
       2, 0, 3, 7, 4, 9, 4, 8, 7, 5, 8, 1, 1, 4, 9, 1, 7, 3, 8, 8, 7, 5,
       2, 4, 3, 1, 2, 8, 6, 1, 0, 4, 2, 4, 3, 8, 2, 0, 5, 8, 0, 9, 9, 5,
       8, 7, 3, 0, 1, 7, 8, 4, 0, 8, 3, 1, 3, 8, 0, 8, 3, 2, 5, 1, 7, 1,
       3, 6, 2, 5, 1, 0, 6, 1, 2, 6, 1, 0, 2, 6, 8, 9, 6, 7, 6, 9, 7, 8,
       9, 7, 6, 5, 0, 6, 1, 4, 0, 4, 4, 3, 5, 5, 8, 5, 0, 8, 7, 0, 9, 0,
       9, 2, 2, 8, 2, 2, 5, 9, 1, 5, 0, 1, 8, 3, 4,

In [25]:
from sklearn.metrics import mean_absolute_error , mean_absolute_percentage_error , r2_score , confusion_matrix , classification_report

In [26]:
mean_absolute_error(y_test,y_pred)

0.10740740740740741

In [27]:
mean_absolute_percentage_error(y_test,y_pred)

0.019140946502057617

In [28]:
r2_score(y_test,y_pred)

0.9369111537123326

In [29]:
confusion_matrix(y_test,y_pred)

array([[55,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 58,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 49,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 64,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1, 54,  0,  0,  1,  1],
       [ 2,  0,  0,  0,  0,  0, 57,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 46,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0, 47,  1],
       [ 0,  0,  0,  0,  0,  2,  0,  2,  1, 46]])